name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Check runner version
      run: "echo Runner version: ${{ runner.os }} ${{ runner.arch }}"

    - name: Run Cypress tests
      run: npx cypress run --reporter mocha-junit-reporter --reporter-options mochaFile=results/test-results.xml

    - name: Debug test results
      run: ls -l results/
      
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: cypress-test-results
        path: results/test-results.xml